package com.expensetracker.app.ui.theme

import androidx.compose.ui.graphics.Color

// Semantic colors used for amounts, charts and flags. These stay constant
// across themes so income/expense always read the same way.
val ExpenseRed = Color(0xFFE53935)
val IncomeGreen = Color(0xFF2E9E4F)

// ---- Light scheme (green seed) ----
val LightPrimary = Color(0xFF2E6B33)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB0F1AE)
val LightOnPrimaryContainer = Color(0xFF002204)
val LightSecondary = Color(0xFF52634F)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD5E8CF)
val LightOnSecondaryContainer = Color(0xFF101F10)
val LightTertiary = Color(0xFF38656A)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFBCEBF0)
val LightOnTertiaryContainer = Color(0xFF002022)
val LightBackground = Color(0xFFFCFDF6)
val LightOnBackground = Color(0xFF1A1C19)
val LightSurface = Color(0xFFFCFDF6)
val LightOnSurface = Color(0xFF1A1C19)
val LightSurfaceVariant = Color(0xFFDEE5D9)
val LightOnSurfaceVariant = Color(0xFF424940)
val LightOutline = Color(0xFF72796F)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF6F7F0)
val LightSurfaceContainer = Color(0xFFF0F2EA)
val LightSurfaceContainerHigh = Color(0xFFEAECE5)
val LightSurfaceContainerHighest = Color(0xFFE4E7DF)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

// ---- Dark scheme ----
val DarkPrimary = Color(0xFF95D593)
val DarkOnPrimary = Color(0xFF003909)
val DarkPrimaryContainer = Color(0xFF17531E)
val DarkOnPrimaryContainer = Color(0xFFB0F1AE)
val DarkSecondary = Color(0xFFB9CCB4)
val DarkOnSecondary = Color(0xFF253423)
val DarkSecondaryContainer = Color(0xFF3B4B39)
val DarkOnSecondaryContainer = Color(0xFFD5E8CF)
val DarkTertiary = Color(0xFFA0CFD4)
val DarkOnTertiary = Color(0xFF00363B)
val DarkTertiaryContainer = Color(0xFF1F4D52)
val DarkOnTertiaryContainer = Color(0xFFBCEBF0)
val DarkBackground = Color(0xFF11140F)
val DarkOnBackground = Color(0xFFE2E3DD)
val DarkSurface = Color(0xFF11140F)
val DarkOnSurface = Color(0xFFE2E3DD)
val DarkSurfaceVariant = Color(0xFF424940)
val DarkOnSurfaceVariant = Color(0xFFC2C9BD)
val DarkOutline = Color(0xFF8C9388)
val DarkSurfaceContainerLowest = Color(0xFF0C0F0A)
val DarkSurfaceContainerLow = Color(0xFF1A1C19)
val DarkSurfaceContainer = Color(0xFF1E201D)
val DarkSurfaceContainerHigh = Color(0xFF282B27)
val DarkSurfaceContainerHighest = Color(0xFF333631)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
